version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - ./go-crud-app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
    env_file:
      - ./go-crud-app/.env
    depends_on:
      - db

volumes:
  postgres_data:
